spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qms?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: qwe123
  redis:
    port: 6379
    host: 127.0.0.1
    password:
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false


#security:
#  basic:
#    enabled: false

server:
  port: 8080


