spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 使用 Druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/qms?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: qwe123
  redis:
    port: 6379
    host: 127.0.0.1
    password:
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      cache: false


#security:
#  basic:
#    enabled: false

server:
  port: 8080

# alibaba druid
druid:
  initialSize: 5
  minIdle: 5
  maxActive: 1000
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计，'wall' 用于防火墙
  filters: stat,wall,log4j
  # 通过 connectProperties 属性来打开 mergeSql 功能；慢 SQL 记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个 DruidDataSource 的监控数据
  useGlobalDataSourceStat: true


